FROM java:8-jre
MAINTAINER  whp <1032998173@qq.com>

ADD ./jar/pig-auth.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.7.1
.jar", "-Dpinpoint.agentId=pig-auth", "-Dpinpoint.applicationName=AUTH", "-jar", "/app/pig-auth.jar"]
